version: '3.7'

services:
  client:
    ports: 
      - "8080:80"
    build:
      context: ./table-example-client
      args:
        api_url: "http://localhost:8081"
    depends_on:
      - server

  server:
    ports: 
      - "8081:8081"
    build:
      context: ./table-example-server
    environment:
      SERVER_PORT: 8081
