version: '3.7'

services:
  client:
    ports: 
      - "8080:80"
    build:
      context: ./table-example-client
    depends_on:
      - server

  server:
    ports: 
      - "8081:8081"
    build:
      context: ./table-example-server
